- hosts: "{{ variable_host | default('server') }}"
  vars:
    server_name: "{{ inventory_hostname }}"
    document_root: /var/www/booktool
  tasks:
    - name: Ensure Nginx is at the latest version
      apt: name=nginx state=latest
    - name: Allow Nginx through ufw firewall
      ufw:
        rule: allow
        name: Nginx Full
        state: enabled
    - name: Setup Nginx appserver site
      template:
        src: ./nginx.conf.j2
        dest: /etc/nginx/sites-available/booktool
      notify: Restart Nginx
    - name: Enable Nginx site
      file:
        src: /etc/nginx/sites-available/booktool
        dest: /etc/nginx/sites-enabled/booktool
        state: link
      notify: Restart Nginx
    - name: Start Nginx
      service:
          name: nginx
          state: started

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
